social:
  - title: Facebook
    icon: facebook
    url: http://facebook.com/XX
  - title: Instagram
    icon: instagram
    url: https://instagram.com/XX
  - title: Mastodon
    icon: mastodon
    url: http://mastodon.social/XX
  - title: Xing
    icon: xing
    url: http://xing.com/XX
  - title: YouTube
    icon: youtube
    url: https://youtube.com/XX